version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - .:/app
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    ports:
      - 25060:25060
    environment:
      - MYSQL_DATABASE=${DB_HOSTNAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
